- name: common core software
  hosts: all
  tasks:
    - name: Install a list of packages common to all targets  
      apt:
        pkg:
        - python-dev       
        - python-virtualenv
        
- name: docker stuff
  hosts: pitft
  tasks:
    - apt:
        pkg:
        - docker-py
        
        
