- name: common core software
  hosts: all
  tasks:
  - name: Install a list of packages common to all targets  
    apt:
      pkg:
      - python3-dev
      - python3-pip
      - python3-virtualenv
        
- name: python docker stuff
  hosts: pitft
  tasks: 
  - name: Install python package needed by the docker-sphere
    pip:
      name: docker
