- name: apt dist upgrade
  hosts: all
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
        autoremove: true
        
        
