- name: install docker
  hosts: all
  tasks:
    - debug:
        msg: "instructions from https://withblue.ink/2020/06/24/docker-and-docker-compose-on-raspberry-pi-os.html"


     
    - name: Install a list of packages
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        
    - name: Get the Docker signing key for packages
      apt_key:
        url: https://download.docker.com/linux/raspbian/gpg
        state: present
