# https://docs.docker.com/engine/install/debian/
# https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script

- name: install docker
  hosts: all
  tasks:
     
    - name:  fetch installer from docker.com
      command: curl -fsSL https://get.docker.com -o get-docker.sh
      
    - name: try docker hello world to see if docker is functional
      command: docker run hello-world
      register: hello
      failed_when: False

    - name: this is dumb
      command: sh get-docker.sh
      failed_when: False
      register: getdocker
      when: not hello.rc == 0

    - debug:
        msg: "{{ getdocker }}"
      when: not hello.rc == 0

        
    - name: bounce to make docker happy and me unhappy
      reboot:
      when: not hello.rc == 0

    - name: try docker hello world after reboot to see if docker is functional
      command: docker run hello-world


