# https://docs.docker.com/engine/install/debian/
# https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script

- name: install docker
  hosts: all
  tasks:
     
    - name:  install from docker.com
      command: curl -fsSL https://get.docker.com -o get-docker.sh
      
    - name: test
      command: pwd
      
    - name: test2
      command: ls -l
      


