# https://docs.docker.com/engine/install/debian/
# https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script

- name: install docker
  hosts: all
  tasks:
     
    - name:  fetch installer from docker.com
      command: curl -fsSL https://get.docker.com -o get-docker.sh
      
    - name: this is dumb
      command: sh get-docker.sh
      


