# https://docs.docker.com/engine/install/debian/
# https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script

- name: install docker
  hosts: all
  tasks:
     
    - name:  fetch installer from docker.com
      command: curl -fsSL https://get.docker.com -o get-docker.sh
      
    - name: this is dumb
      command: sh get-docker.sh
      failed_when: False
      register: result
      
    - debug:
        msg: "{{ result }}"
        
    - name: bounce to make docker happy and me unhappy
      reboot:
      when: not result.rc == 0

    - name: this is dumber
      command: sh get-docker.sh
      register: result2
      when: not result.rc == 0
      
    - debug:
        msg: "{{ result2 }}"
      when: not result.rc == 0


