- name: Uptime
  hosts: all
  tasks:
    - name: uptime
      command: uptime
      failed_when: False

        
    - name: check docker engine responsiveness
      command: docker ps
      failed_when: False
      
