- name: set hostname based on MAC
  hosts: all

  vars:
    mac2hostname:
      "b8:27:eb:06:d5:d5": 
        name: "pia"
      "b8:27:eb:ca:9f:5a":
        name: "pib"
      "b8:27:eb:a1:54:0c":
        name: "pic"
      "b8:27:eb:e4:31:3a":
        name: "pid"
      "b8:27:eb:11:c1:19":
        name: "pie"
      "b8:27:eb:0a:c4:ea":
        name: "pif"
      "b8:27:eb:59:cc:89":
        name: "pig"
      "b8:27:eb:53:83:54":
        name: "pih"
      "b8:27:eb:1d:65:93":
        name: "pii"
      
      
  tasks:

    - debug:
        msg: "I think I am {{ mac2hostname[hostvars[inventory_hostname].ansible_default_ipv4.macaddress].name }}"
