- name: enable SPI interface
  hosts: all

  tasks:

    - name: get SPI status 
      command: raspi-config nonint get_spi
      register: result_before
      changed_when: False

    - name: set SPI enabled 
      command: raspi-config nonint do_spi 0
      register: result_after
      
    - debug:
        msg: "{{ result_after }}"

    - name: get SPI status 
      command: raspi-config nonint get_spi
      changed_when: False
