- name: enable SPI interface
  hosts: all

  tasks:

    - name: get SPI status 
      command: raspi-config nonint get_spi

    - name: set SPI enabled 
      command: raspi-config nonint do_spi 0

    - name: get SPI status 
      command: raspi-config nonint get_spi

