- name: enable SPI interface
  hosts: all

  tasks:

    - name: get SPI status 
      command: raspi-config nonint get_spi
      register: result
      changed_when: False

    - name: set SPI enabled 
      command: raspi-config nonint do_spi 0
      when: result.stdout == "1"
      
    - debug:
        msg: "{{ result }}"

    - name: get SPI status 
      command: raspi-config nonint get_spi
      changed_when: False
