https://wiki.debian.org/VirtualBox#Debian_10_.22Buster.22

Add virtualbox.list to /etc/apt/sources.list.d

deb http://download.virtualbox.org/virtualbox/debian buster contrib
Add Oracle VirtualBox public key:

wget https://www.virtualbox.org/download/oracle_vbox_2016.asc
sudo apt-key add oracle_vbox_2016.asc
Install virtualbox-6.1

sudo apt-get update
sudo apt-get install virtualbox-6.1


- name: apt dist upgrade
  hosts: all
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
        
        
